# Generated by Django 3.2 on 2021-05-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.TextField(blank=True, default='Hey There I am on fakebook', max_length=300)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('pic', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
